apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo110
  labels:
    app: demo110
  namespace: default

spec:
  replicas: 2
  selector:
    matchLabels:
      app: demo110
  template:
    metadata:
      labels:
        app: demo110
    spec:
      containers:
      - image: 192.168.0.216:8888/library/demo:v2
        name: demo110
      restartPolicy: Always
